name: Coverage

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: '18.15.0'
      - name: Install dev-dependencies
        run: npm install --only=dev
      - name: Run test with coverage
        run: npm run test:coverage
      - name: Generate coveralls report
        env:
          COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_REPO_TOKEN }}
        run: npm run coveralls