name: Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: '22'
          check-latest: true
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run test with coverage
        run: npm run test:coverage
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info