name: Generate and Deploy Documentation

on:
  push:
    branches:
      - v1.1.2

jobs:
    documentation:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v3.8.1
          with:
            node-version: '18.15.0'
        - name: Install dependencies and generate documentation
          run: |
            npm install --only=dev
            npm install -g typedoc@0.25.1
            npm install -g typedoc-theme-hierarchy@4.1.1
            typedoc --entryPoints ./src --entryPointStrategy expand --out ./docs --plugin typedoc-theme-hierarchy --theme hierarchy --name websocket-ts
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@4.1.5
          with:
            branch: gh-pages
            folder: docs
