name: Generate and Deploy Documentation

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: '22'
          check-latest: true
      - name: Install dependencies and generate documentation
        run: |
          npm ci
          npm i -D typedoc@0.28.9 typedoc-theme-hierarchy@6.0.0
          npx typedoc --tsconfig tsconfig.esm.json \
            --exclude "src/**/index.ts" \
            --entryPoints ./src \
            --entryPointStrategy expand \
            --out ./docs \
            --plugin typedoc-theme-hierarchy \
            --theme hierarchy \
            --name websocket-ts
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: docs
          target-folder: docs
