name: Generate and Deploy Documentation

on:
  push:
    branches:
      - master

jobs:
    documentation:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4.2.0
          with:
            node-version: '22.14.0'
        - name: Install dependencies and generate documentation
          run: |
            npm install
            npm install typedoc@0.27.7
            npm install typedoc-theme-hierarchy@5.0.4
            npx typedoc --tsconfig tsconfig.esm.json --exclude "src/**/index.ts" --entryPoints ./src --entryPointStrategy expand --out ./docs --plugin typedoc-theme-hierarchy --theme hierarchy --name websocket-ts
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@v4.7.2
          with:
            branch: gh-pages
            folder: docs
            target-folder: docs
