name: Generate and Deploy Documentation

on:
  push:
    branches:
      - master

jobs:
    documentation:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v3.8.1
          with:
            node-version: '18.15.0'
        - name: Install dependencies and generate documentation
          run: |
            npm install
            npm install typedoc@0.25.1
            npm install typedoc-theme-hierarchy@4.1.1
            npx typedoc --entryPoints ./src --entryPointStrategy expand --out ./docs --plugin typedoc-theme-hierarchy --theme hierarchy --name websocket-ts
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@v4.4.3
          with:
            branch: gh-pages
            folder: docs
            target-folder: docs
