name: Lint

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.2.0
        with:
          node-version: '22.14.0'
      - name: Install dev-dependencies
        run: npm install --only=dev
      - name: Run lint
        run: npm run lint