name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: '22'
          check-latest: true
          cache: 'npm'
      - name: Install dev-dependencies
        run: npm ci --only=dev
      - name: Run lint
        run: npm run lint
